#!/usr/bin/env python3
"""Step 2_2: Assign Dawn Chorus points to LRT-majority grid cells and LRT polygons.

Workflow
--------
1. Read the clean Dawn Chorus metadata generated by Step 1.
2. Read the 100 m INSPIRE grid and the grid-level majority-formation table
   generated by Step 2_1.
3. Ignore all grid cells without a majority formation.
4. Assign each Dawn Chorus point to a retained grid cell.
5. For points inside a retained grid cell, test whether they also fall inside
   one or more cleaned LRT polygons generated by Step 2_0.
6. Write:
   - one clean point-level output for later master-table integration;
   - one detailed point-to-LRT match table;
   - one processing log;
   - one JSON state file.

Incremental behaviour
---------------------
- On the first run, all valid Dawn Chorus IDs are processed.
- On later runs, only new IDs are appended when the spatial reference inputs
  are unchanged.
- If the grid, Step 2_1 majority table, or cleaned LRT GeoPackage changes,
  all point outputs are rebuilt because previous spatial assignments may no
  longer be valid.
- Use --force to rebuild unconditionally.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys

os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")
from pathlib import Path
from typing import Any

import geopandas as gpd
import pandas as pd

from common import atomic_write_csv, atomic_write_json


def load_config(config_path: Path) -> dict[str, Any]:
    if not config_path.is_file():
        raise FileNotFoundError(f"Config file not found: {config_path}")

    with config_path.open("r", encoding="utf-8") as file:
        config = json.load(file)

    section = config.get("point_lrt_assignment")
    if not isinstance(section, dict):
        raise KeyError(
            "Missing 'point_lrt_assignment' section in config.json."
        )

    required = [
        "metadata_csv",
        "grid_gpkg",
        "grid_majority_csv",
        "lrt_gpkg",
        "output_csv",
        "matches_csv",
        "log_csv",
    ]
    missing = [key for key in required if not section.get(key)]
    if missing:
        raise KeyError(
            "Missing required point_lrt_assignment key(s): "
            + ", ".join(missing)
        )

    return config


def file_fingerprint(
    path: Path,
    hash_bytes: int = 1024 * 1024,
) -> dict[str, Any]:
    if not path.is_file():
        raise FileNotFoundError(f"Input file not found: {path}")

    stat = path.stat()
    digest = hashlib.sha256()

    with path.open("rb") as file:
        digest.update(file.read(hash_bytes))
        if stat.st_size > hash_bytes:
            file.seek(max(0, stat.st_size - hash_bytes))
            digest.update(file.read(hash_bytes))

    return {
        "path": str(path.resolve()),
        "size_bytes": stat.st_size,
        "mtime_ns": stat.st_mtime_ns,
        "edge_sha256": digest.hexdigest(),
    }


def load_previous_state(state_file: Path) -> dict[str, Any] | None:
    if not state_file.is_file():
        return None

    try:
        with state_file.open("r", encoding="utf-8") as file:
            return json.load(file)
    except (OSError, json.JSONDecodeError):
        return None


def spatial_inputs_changed(
    previous_state: dict[str, Any] | None,
    current_spatial_state: dict[str, Any],
) -> bool:
    if previous_state is None:
        return True

    return previous_state.get("spatial_inputs") != current_spatial_state


def read_existing_ids(output_csv: Path) -> set[int]:
    if not output_csv.is_file():
        return set()

    existing = pd.read_csv(
        output_csv,
        usecols=["id"],
        low_memory=False,
    )
    ids = (
        pd.to_numeric(existing["id"], errors="coerce")
        .dropna()
        .astype("int64")
    )
    return set(ids.tolist())


def load_points(metadata_csv: Path) -> pd.DataFrame:
    points = pd.read_csv(metadata_csv, low_memory=False)

    required = {"id", "lat", "lon"}
    missing = required - set(points.columns)
    if missing:
        raise ValueError(
            "Missing required metadata columns: "
            + ", ".join(sorted(missing))
        )

    points = points.copy()
    points["id"] = pd.to_numeric(
        points["id"], errors="coerce"
    ).astype("Int64")
    points["lat"] = pd.to_numeric(
        points["lat"], errors="coerce"
    )
    points["lon"] = pd.to_numeric(
        points["lon"], errors="coerce"
    )

    points = points[points["id"].notna()].copy()
    points = points.drop_duplicates("id", keep="first")

    return points


def load_grid_with_majority(
    grid_gpkg: Path,
    grid_layer: str,
    grid_id_column: str,
    grid_majority_csv: Path,
) -> gpd.GeoDataFrame:
    grid = gpd.read_file(
        grid_gpkg,
        layer=grid_layer,
        engine="pyogrio",
    )

    if grid_id_column not in grid.columns:
        raise ValueError(
            f"Grid ID column '{grid_id_column}' not found. "
            f"Available columns: {list(grid.columns)}"
        )

    majority = pd.read_csv(grid_majority_csv, low_memory=False)

    required_majority = {
        grid_id_column,
        "majority_formation",
    }
    missing = required_majority - set(majority.columns)
    if missing:
        raise ValueError(
            "Missing required grid-majority columns: "
            + ", ".join(sorted(missing))
        )

    majority = majority[
        majority["majority_formation"].notna()
    ].copy()

    majority = majority.drop_duplicates(
        grid_id_column,
        keep="first",
    )

    grid = grid[[grid_id_column, "geometry"]].merge(
        majority,
        on=grid_id_column,
        how="inner",
    )

    if grid.empty:
        raise ValueError(
            "No grid cells with a majority formation were found."
        )

    return gpd.GeoDataFrame(
        grid,
        geometry="geometry",
        crs=grid.crs,
    )


def load_lrt(
    lrt_gpkg: Path,
    lrt_layer: str,
    target_crs: Any,
) -> gpd.GeoDataFrame:
    lrt = gpd.read_file(
        lrt_gpkg,
        layer=lrt_layer,
        engine="pyogrio",
    )

    required = {
        "src_id",
        "LRT_code",
        "Formation",
        "conservation_status",
        "mapping_year",
        "geometry",
    }
    missing = required - set(lrt.columns)
    if missing:
        raise ValueError(
            "Missing required LRT columns: "
            + ", ".join(sorted(missing))
        )

    if lrt.crs is None:
        raise ValueError("The cleaned LRT layer has no CRS.")

    if lrt.crs != target_crs:
        lrt = lrt.to_crs(target_crs)

    return lrt[
        [
            "src_id",
            "LRT_code",
            "Formation",
            "conservation_status",
            "mapping_year",
            "geometry",
        ]
    ].copy()


def build_point_geodataframe(
    points: pd.DataFrame,
    target_crs: Any,
) -> gpd.GeoDataFrame:
    valid = points[
        points["lat"].notna()
        & points["lon"].notna()
    ].copy()

    geometry = gpd.points_from_xy(
        valid["lon"],
        valid["lat"],
        crs="EPSG:4326",
    )

    return gpd.GeoDataFrame(
        valid,
        geometry=geometry,
        crs="EPSG:4326",
    ).to_crs(target_crs)


def assign_points_to_grid(
    points_gdf: gpd.GeoDataFrame,
    grid: gpd.GeoDataFrame,
    grid_id_column: str,
) -> gpd.GeoDataFrame:
    result = gpd.sjoin(
        points_gdf,
        grid,
        how="left",
        predicate="within",
    )

    result = result.drop(columns=["index_right"], errors="ignore")

    duplicates = result["id"].duplicated(keep=False)
    if duplicates.any():
        result = (
            result.sort_values([ "id", grid_id_column ])
            .drop_duplicates("id", keep="first")
            .copy()
        )

    return result


def assign_points_to_lrt(
    points_in_grid: gpd.GeoDataFrame,
    lrt: gpd.GeoDataFrame,
) -> pd.DataFrame:
    if points_in_grid.empty:
        return pd.DataFrame(
            columns=[
                "id",
                "src_id",
                "LRT_code",
                "Formation",
                "conservation_status",
                "mapping_year",
            ]
        )

    matches = gpd.sjoin(
        points_in_grid[["id", "geometry"]],
        lrt,
        how="inner",
        predicate="within",
    )

    matches = matches.drop(
        columns=["index_right", "geometry"],
        errors="ignore",
    )

    matches = matches.drop_duplicates(
        subset=[
            "id",
            "src_id",
            "LRT_code",
            "Formation",
            "conservation_status",
            "mapping_year",
        ]
    )

    return pd.DataFrame(matches)


def summarise_lrt_matches(matches: pd.DataFrame) -> pd.DataFrame:
    if matches.empty:
        return pd.DataFrame(
            columns=[
                "id",
                "inside_lrt_polygon",
                "lrt_polygon_count",
                "lrt_code_count",
                "lrt_formation_count",
                "lrt_status_count",
                "lrt_mapping_year_count",
                "lrt_codes",
                "lrt_formations",
                "lrt_conservation_statuses",
                "lrt_mapping_years",
            ]
        )

    def joined_unique(values: pd.Series) -> str:
        cleaned = (
            values.dropna()
            .astype(str)
            .drop_duplicates()
            .sort_values()
        )
        return "|".join(cleaned.tolist())

    summary = (
        matches.groupby("id")
        .agg(
            lrt_polygon_count=("src_id", "nunique"),
            lrt_code_count=("LRT_code", "nunique"),
            lrt_formation_count=("Formation", "nunique"),
            lrt_status_count=("conservation_status", "nunique"),
            lrt_mapping_year_count=("mapping_year", "nunique"),
            lrt_codes=("LRT_code", joined_unique),
            lrt_formations=("Formation", joined_unique),
            lrt_conservation_statuses=(
                "conservation_status",
                joined_unique,
            ),
            lrt_mapping_years=("mapping_year", joined_unique),
        )
        .reset_index()
    )

    summary["inside_lrt_polygon"] = True
    return summary


def build_outputs(
    source_points: pd.DataFrame,
    grid_assignments: gpd.GeoDataFrame,
    lrt_matches: pd.DataFrame,
    grid_id_column: str,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    match_summary = summarise_lrt_matches(lrt_matches)

    grid_columns = [
        column
        for column in grid_assignments.columns
        if column not in {
            "geometry",
            "lat",
            "lon",
            "datetime",
        }
    ]

    point_output = source_points.merge(
        pd.DataFrame(grid_assignments[grid_columns]),
        on="id",
        how="left",
    )

    point_output["inside_majority_grid"] = (
        point_output[grid_id_column].notna()
    )

    point_output = point_output.merge(
        match_summary,
        on="id",
        how="left",
    )

    point_output["inside_lrt_polygon"] = (
        point_output["inside_lrt_polygon"]
        .fillna(False)
        .astype(bool)
    )

    count_columns = [
        "lrt_polygon_count",
        "lrt_code_count",
        "lrt_formation_count",
        "lrt_status_count",
        "lrt_mapping_year_count",
    ]
    for column in count_columns:
        point_output[column] = (
            point_output[column]
            .fillna(0)
            .astype("Int64")
        )

    clean_columns = [
        "id",
        grid_id_column,
        "inside_majority_grid",
        "inside_lrt_polygon",
    ]

    inherited_columns = [
        column
        for column in point_output.columns
        if column.startswith("majority_")
        or column in {
            "formation_count",
            "multiple_formations_in_cell",
        }
    ]

    diagnostic_columns = [
        "lrt_polygon_count",
        "lrt_code_count",
        "lrt_formation_count",
        "lrt_status_count",
        "lrt_mapping_year_count",
        "lrt_codes",
        "lrt_formations",
        "lrt_conservation_statuses",
        "lrt_mapping_years",
    ]

    output = point_output[
        clean_columns
        + [
            column
            for column in inherited_columns
            if column not in clean_columns
        ]
        + diagnostic_columns
    ].copy()

    log = source_points[
        ["id", "datetime", "lat", "lon"]
    ].copy()

    log = log.merge(
        output,
        on="id",
        how="left",
    )

    log["valid_coordinates"] = (
        log["lat"].notna()
        & log["lon"].notna()
    )

    log["processing_status"] = "processed"
    log.loc[
        ~log["valid_coordinates"],
        "processing_status",
    ] = "missing_coordinates"
    log.loc[
        log["valid_coordinates"]
        & ~log["inside_majority_grid"],
        "processing_status",
    ] = "outside_majority_grid"
    log.loc[
        log["inside_majority_grid"]
        & ~log["inside_lrt_polygon"],
        "processing_status",
    ] = "inside_majority_grid_outside_lrt"
    log.loc[
        log["inside_lrt_polygon"],
        "processing_status",
    ] = "inside_lrt_polygon"

    return output, lrt_matches, log


def read_optional_csv(path: Path) -> pd.DataFrame:
    if not path.is_file() or path.stat().st_size == 0:
        return pd.DataFrame()
    return pd.read_csv(path, low_memory=False, encoding="utf-8-sig")


def read_ids_file(path: Path | None) -> set[int] | None:
    if path is None:
        return None
    frame = pd.read_csv(path, low_memory=False)
    for column in ("dawn_chorus_id", "id"):
        if column in frame.columns:
            return set(
                pd.to_numeric(frame[column], errors="coerce")
                .dropna()
                .astype(int)
            )
    raise KeyError(f"No dawn_chorus_id/id column in {path}")


def upsert_rows(
    path: Path,
    replacement: pd.DataFrame,
    target_ids: set[int],
    rebuild: bool,
) -> pd.DataFrame:
    existing = pd.DataFrame() if rebuild else read_optional_csv(path)
    if existing.empty:
        merged = replacement.copy()
    else:
        existing_ids = pd.to_numeric(existing["id"], errors="coerce")
        retained = existing.loc[~existing_ids.isin(target_ids)]
        merged = pd.concat([retained, replacement], ignore_index=True)
    if "id" in merged.columns:
        merged = merged.sort_values(
            "id",
            key=lambda values: pd.to_numeric(values, errors="coerce"),
        ).reset_index(drop=True)
    atomic_write_csv(merged, path)
    return merged


def write_state(
    state_file: Path,
    metadata_csv: Path,
    spatial_state: dict[str, Any],
    processed_ids: int,
    rebuild: bool,
) -> None:
    state = {
        "metadata_input": file_fingerprint(metadata_csv),
        "spatial_inputs": spatial_state,
        "result": {
            "processed_ids_total": processed_ids,
            "last_run_was_full_rebuild": rebuild,
        },
    }

    atomic_write_json(state_file, state)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Step 2_2: assign Dawn Chorus points to majority-grid cells "
            "and cleaned LRT polygons."
        )
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "config.json",
    )
    parser.add_argument("--force", action="store_true")
    parser.add_argument(
        "--ids-file",
        type=Path,
        help="Optional run-plan CSV containing new/changed/deleted IDs.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    try:
        config = load_config(args.config)
        settings = config["point_lrt_assignment"]

        metadata_csv = Path(settings["metadata_csv"])

        grid_gpkg = Path(settings["grid_gpkg"])
        grid_layer = settings.get("grid_layer", "grid")
        grid_id_column = settings.get("grid_id_column", "grid_id")
        grid_majority_csv = Path(settings["grid_majority_csv"])

        lrt_gpkg = Path(settings["lrt_gpkg"])
        lrt_layer = settings.get("lrt_layer", "lrt")

        output_csv = Path(settings["output_csv"])
        matches_csv = Path(settings["matches_csv"])
        log_csv = Path(settings["log_csv"])

        status_dir = Path(config["status_dir"])
        state_file = Path(
            settings.get(
                "state_file",
                status_dir / "step_2_2_point_lrt_assignment_state.json",
            )
        )

        spatial_state = {
            "grid_gpkg": file_fingerprint(grid_gpkg),
            "grid_majority_csv": file_fingerprint(grid_majority_csv),
            "lrt_gpkg": file_fingerprint(lrt_gpkg),
            "settings": {
                "grid_layer": grid_layer,
                "grid_id_column": grid_id_column,
                "lrt_layer": lrt_layer,
            },
        }

        previous_state = load_previous_state(state_file)
        rebuild = (
            args.force
            or spatial_inputs_changed(previous_state, spatial_state)
            or not output_csv.is_file()
            or not matches_csv.is_file()
            or not log_csv.is_file()
        )

        if rebuild:
            existing_ids: set[int] = set()
            print("Step 2_2 will perform a full rebuild.")
        else:
            existing_ids = read_existing_ids(output_csv)
            print(
                "Step 2_2 will process only IDs not present "
                "in the existing output."
            )

        points = load_points(metadata_csv)
        requested_ids = read_ids_file(args.ids_file)
        if rebuild:
            target_ids = set(points["id"].dropna().astype(int))
        elif requested_ids is not None:
            target_ids = requested_ids
        else:
            target_ids = set(
                points.loc[~points["id"].isin(existing_ids), "id"]
                .dropna()
                .astype(int)
            )
        new_points = points.loc[points["id"].isin(target_ids)].copy()

        if not target_ids:
            print("Step 2_2 skipped: no new Dawn Chorus IDs found.")
            print(f"Output : {output_csv}")
            print(f"Matches: {matches_csv}")
            print(f"Log    : {log_csv}")
            return 0

        if new_points.empty:
            output = pd.DataFrame()
            matches = pd.DataFrame()
            log = pd.DataFrame()
        else:
            grid = load_grid_with_majority(
                grid_gpkg=grid_gpkg,
                grid_layer=grid_layer,
                grid_id_column=grid_id_column,
                grid_majority_csv=grid_majority_csv,
            )

            lrt = load_lrt(
                lrt_gpkg=lrt_gpkg,
                lrt_layer=lrt_layer,
                target_crs=grid.crs,
            )

            points_gdf = build_point_geodataframe(
                new_points,
                target_crs=grid.crs,
            )

            grid_assignments = assign_points_to_grid(
                points_gdf=points_gdf,
                grid=grid,
                grid_id_column=grid_id_column,
            )

            points_in_grid = grid_assignments[
                grid_assignments[grid_id_column].notna()
            ].copy()

            lrt_matches = assign_points_to_lrt(
                points_in_grid=points_in_grid,
                lrt=lrt,
            )

            output, matches, log = build_outputs(
                source_points=new_points,
                grid_assignments=grid_assignments,
                lrt_matches=lrt_matches,
                grid_id_column=grid_id_column,
            )

        merged_output = upsert_rows(
            output_csv,
            output,
            target_ids,
            rebuild,
        )
        upsert_rows(matches_csv, matches, target_ids, rebuild)
        upsert_rows(log_csv, log, target_ids, rebuild)

        processed_ids_total = int(
            pd.to_numeric(
                merged_output.get("id", pd.Series(dtype=float)),
                errors="coerce",
            ).nunique()
        )

        write_state(
            state_file=state_file,
            metadata_csv=metadata_csv,
            spatial_state=spatial_state,
            processed_ids=processed_ids_total,
            rebuild=rebuild,
        )

        print("\nStep 2_2 completed.")
        print(f"IDs reconciled                 : {len(target_ids):,}")
        print(f"Current IDs recalculated       : {len(output):,}")
        if not output.empty:
            print(
                "Inside majority grid           : "
                f"{output['inside_majority_grid'].sum():,}"
            )
            print(
                "Inside at least one LRT polygon: "
                f"{output['inside_lrt_polygon'].sum():,}"
            )
            print(
                "Outside majority grid          : "
                f"{(~output['inside_majority_grid']).sum():,}"
            )
        print(f"Output CSV                     : {output_csv}")
        print(f"Detailed matches CSV           : {matches_csv}")
        print(f"Processing log CSV             : {log_csv}")
        print(f"State file                     : {state_file}")

        return 0

    except Exception as exc:
        print(f"ERROR in Step 2_2: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
